# Generated by Django 2.2.2 on 2020-02-23 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('purpose', models.CharField(max_length=250)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_visit_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(blank=True, max_length=250, null=True)),
                ('notes', models.CharField(blank=True, max_length=250, null=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.Visit')),
            ],
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RS', models.CharField(choices=[('1', 'RHONCHI'), ('2', 'CREEPS'), ('3', 'AIR ENTRY'), ('4', 'OTHER')], max_length=100)),
                ('RS_comments', models.CharField(blank=True, max_length=250, null=True)),
                ('CVC', models.CharField(choices=[('1', 'HR'), ('2', 'OTHER')], max_length=100)),
                ('CVC_comments', models.CharField(blank=True, max_length=250, null=True)),
                ('ABD', models.CharField(choices=[('1', 'LIVER'), ('2', 'SPLEEN'), ('3', 'STOMCH'), ('4', 'INTESTINE'), ('5', 'KIDENY'), ('6', 'UTERINE'), ('7', 'GENITLE'), ('8', 'OTHER')], max_length=100)),
                ('ABD_comments', models.CharField(blank=True, max_length=250, null=True)),
                ('CNS', models.CharField(choices=[('1', 'SENSORY'), ('2', 'MOTOR'), ('3', 'OTHER')], max_length=100)),
                ('CNS_comments', models.CharField(blank=True, max_length=250, null=True)),
                ('SKIN', models.CharField(choices=[('1', 'COLOUR'), ('2', 'ERUPTION'), ('3', 'OTHER')], max_length=100)),
                ('SKIN_comments', models.CharField(blank=True, max_length=250, null=True)),
                ('GENREAL_comments', models.CharField(max_length=250)),
                ('HEAD_comments', models.CharField(max_length=250)),
                ('EXTRIMTY_comments', models.CharField(max_length=250)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.Visit')),
            ],
        ),
    ]
