# Generated by Django 2.2.2 on 2020-02-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provisional', models.CharField(max_length=250)),
                ('final', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_report', models.CharField(choices=[('1', 'Blood'), ('2', 'Urine'), ('3', 'X-Ray'), ('4', 'MRI'), ('5', 'CT scan'), ('6', 'Biopsy'), ('7', 'None')], max_length=100)),
                ('comments', models.CharField(max_length=250)),
            ],
        ),
    ]
