# Generated by Django 2.2.2 on 2020-02-24 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0003_auto_20200223_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=250)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_visit', to='visit.Visit')),
            ],
        ),
    ]
