# Generated by Django 2.2.2 on 2020-02-23 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0003_customuser_is_staff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoctoProfile',
            new_name='DoctorProfile',
        ),
    ]
