# Generated by Django 2.2.2 on 2020-02-23 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0004_auto_20200223_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='middel_name',
        ),
    ]
