# Generated by Django 2.2.2 on 2020-02-23 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0005_auto_20200223_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='assigned_doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_doctor_profile', to='user_manager.DoctorProfile'),
        ),
    ]
