# Generated by Django 2.2.2 on 2020-02-23 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_manager', '0006_studentprofile_assigned_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='student_mail',
        ),
    ]
